/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'Georgia', 'serif'],
        display: ['Space Grotesk', 'Inter', 'sans-serif'],
      },
      colors: {
        brand: {
          cream: '#FFF9E6',
          sand: '#FFF3CC',
          taupe: '#E6D9A8',
          stone: '#C4B978',
          earth: '#A69F48',
          charcoal: '#2B4A6F',
          espresso: '#1A3A5C',
          navy: '#0F2A4A',
          gold: '#FFD93D',
          goldLight: '#FFE566',
          copper: '#F4A900',
          blue: '#3B82F6',
          blueLight: '#60A5FA',
          blueDark: '#1E40AF',
          ocean: '#0EA5E9',
          sunshine: '#FBBF24',
          honey: '#F59E0B',
        },
        pastel: {
          peach: '#FFE4B5',
          peachLight: '#FFECCC',
          peachDark: '#FFD27A',
          yellow: '#FEF3C7',
          yellowLight: '#FEF9E7',
          coral: '#FFB88C',
          coralLight: '#FFCCA8',
          mint: '#BAE6FD',
          mintLight: '#E0F2FE',
          skyBlue: '#7DD3FC',
          skyBlueLight: '#BAE6FD',
          lavender: '#C4B5FD',
          lavenderLight: '#DDD6FE',
          amber: '#FCD34D',
          amberLight: '#FDE68A',
          orange: '#FBBF24',
          orangeLight: '#FCD34D',
          blue: '#93C5FD',
          blueLight: '#BFDBFE',
          blueDark: '#60A5FA',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.8s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'fade-in-slow': 'fadeIn 1.2s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'floatSlow 8s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'spin-slow': 'spin 20s linear infinite',
        'spin-reverse': 'spinReverse 15s linear infinite',
        'bounce-gentle': 'bounceGentle 2s ease-in-out infinite',
        'pour': 'pour 2s ease-out forwards',
        'bubble': 'bubble 3s ease-in-out infinite',
        'wave': 'wave 4s ease-in-out infinite',
        'drive-in': 'driveIn 3s ease-out forwards',
        'fly-across': 'flyAcross 8s linear infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'rain': 'rain 1s linear infinite',
        'sway': 'sway 4s ease-in-out infinite',
        'morph': 'morph 8s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(5deg)' },
        },
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-10px) rotate(3deg)' },
        },
        spinReverse: {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pour: {
          '0%': { transform: 'translateY(-100%) scaleY(0.8)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'translateY(0) scaleY(1)', opacity: '1' },
        },
        bubble: {
          '0%': { transform: 'translateY(0) scale(1)', opacity: '0.8' },
          '50%': { transform: 'translateY(-50px) scale(1.2)', opacity: '0.6' },
          '100%': { transform: 'translateY(-100px) scale(0.8)', opacity: '0' },
        },
        wave: {
          '0%, 100%': { transform: 'translateX(0) translateY(0)' },
          '25%': { transform: 'translateX(-10px) translateY(5px)' },
          '50%': { transform: 'translateX(0) translateY(10px)' },
          '75%': { transform: 'translateX(10px) translateY(5px)' },
        },
        driveIn: {
          '0%': { transform: 'translateX(200%) scale(0.8)', opacity: '0' },
          '100%': { transform: 'translateX(0) scale(1)', opacity: '1' },
        },
        flyAcross: {
          '0%': { transform: 'translateX(-100%) translateY(0)' },
          '25%': { transform: 'translateX(25% translateY(-20px)' },
          '50%': { transform: 'translateX(50%) translateY(0)' },
          '75%': { transform: 'translateX(75%) translateY(-15px)' },
          '100%': { transform: 'translateX(150%) translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(251, 191, 36, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(251, 191, 36, 0.6)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        rain: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh)', opacity: '0' },
        },
        sway: {
          '0%, 100%': { transform: 'rotate(-2deg)' },
          '50%': { transform: 'rotate(2deg)' },
        },
        morph: {
          '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'glass': 'linear-gradient(135deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.05) 100%)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
